site_name: Go Meme - Dynamic Bonding Curve Documentation
site_url: https://docs.go.meme
site_description: Comprehensive documentation for the Dynamic Bonding Curve Solana program
site_author: Go Meme Team
repo_url: https://github.com/go-meme/gomeme-docs
repo_name: go-meme/gomeme-docs

# Tell MkDocs that markdown files are in the root directory
docs_dir: .

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: vi
          name: Tiếng Việt
          build: true
          nav_translations:
            Home: Trang chủ
            Getting Started: Bắt đầu
            Overview: Tổng quan
            Instructions Reference: Tham chiếu lệnh
            Core Concepts: Khái niệm cốt lõi
            State Accounts: Tài khoản trạng thái
            Bonding Curve Math: Toán học đường cong
            Fee System: Hệ thống phí
            Guides: Hướng dẫn
            Workflows: Quy trình
            Migration: Di chuyển
  - minify:
      minify_html: true

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Tiếng Việt
      link: /vi/
      lang: vi

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/go-meme
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gomeme

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - Welcome: README.md
    - Setup Guide: SETUP.md
  - Getting Started:
    - Overview: 00-overview.md
    - Instructions Reference: 01-instructions.md
  - Core Concepts:
    - State Accounts: 02-state-accounts.md
    - Bonding Curve Math: 03-bonding-curve-math.md
    - Fee System: 04-fee-system.md
  - Guides:
    - Workflows & Examples: 05-workflows.md
    - Migration System: 06-migration.md

copyright: Copyright &copy; 2025 Go Meme
